server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
